### ISSUE TITLE
Can't add recipe to favorites

### ISSUE THREAD

**Issue by axelolsson** [chas-academy/10-recipe-app-zavham#3]
![image](https://user-images.githubusercontent.com/343422/40530849-953c4f18-5ffa-11e8-8db9-3f9367d03b78.png)

Searched for pasta, clicked that recipe and then tried clicking "Add to Favorites".

Error log:
[zavham.chas.academy-1527231943238.log](https://github.com/chas-academy/10-recipe-app-zavham/files/2038312/zavham.chas.academy-1527231943238.log)

**Comment by zavham** [comment]
done
